/**
 * Asana Project Builder
 * 
 * Creates a perfectly structured Asana project from equipment data.
 * Uses the Asana API directly (not CSV import).
 * 
 * Structure:
 *   Project: "DUB069HV - 4th Transformer Commissioning"
 *   ├── Section: Milestones
 *   │   ├── 🏁 Commissioning Kickoff (milestone)
 *   │   ├── ⚡ L3 SAT Complete (milestone)
 *   │   └── ✅ Energization (milestone)
 *   ├── Section: Transformer Bay
 *   │   ├── Surge Arrester 1 (task, 3 days, with test checklist)
 *   │   ├── CT (HV) 1 (task, 2 days)
 *   │   └── Oil Transformer (task, 5 days)
 *   ├── Section: 01A Incomer
 *   │   ├── CT - Protection (task, 2 days)
 *   │   ├── Circuit Breaker (task, 3 days)
 *   │   └── ...
 *   └── ...
 */

import TEST_TEMPLATES from '../data/test_templates.json'
import {
  getWorkspaces, createProject, createSection, createTask,
  createCustomField, addCustomFieldToProject, setDependency,
} from './asanaAPI'

// ─── DISPLAY NAMES & CONFIG ──────────────────────────────────────────────────
const DISPLAY_NAMES = {
  CT: 'CT - Protection', CT_HV: 'CT (HV/Outdoor)', CT_METER: 'CT - Metering',
  NCT: 'NCT / CBCT', NER_CT: 'NER CT', VT: 'VT', VT_HV: 'VT (HV/Outdoor)',
  CIRCUIT_BREAKER: 'Circuit Breaker', EARTH_SWITCH: 'Earth Switch',
  SURGE_ARRESTER: 'Surge Arrester', TRANSFORMER: 'Oil Transformer',
  DRY_TRANSFORMER: 'Dry Transformer', NER: 'NER',
  BUSBAR: 'Busbar', HV_CABLE: 'HV Cable', MV_CABLE: 'MV Cable',
  PQM: 'Power Quality Meter', EPMS: 'EPMS', RELAY: 'Relay / IED',
  CUBICLE: 'Cubicle', PROTECTION_PANEL: 'Protection Panel',
  MK_OLTC_PANEL: 'MK & OLTC Panel', STABILITY_TEST: 'Stability Test',
  SYNCH_CHECK: 'Synch Check', CABLE_DIFF: 'Cable Diff (87L)',
  L4_INTEGRATION: 'L4 Integration', ENERGIZATION: 'Energization',
  SWITCHGEAR_OVERALL: 'Switchgear Overall', AC_DC_CHECKS: 'AC/DC Distribution',
  SCADA: 'SCADA / SAS', ESB_INTERFACE: 'Grid Interface',
  SUBSTATION_CHECKS: 'Substation Checks',
}

const LEVEL_LABELS = {
  L1: 'L1 - Factory Testing', L2: 'L2 - Pre-SAT',
  L3: 'L3 - SAT', L4: 'L4 - FPT', L5: 'L5 - Energization',
}

function getTests(item) {
  if (item.customTests) return item.customTests.filter(t => t.enabled).map(t => [t.level, t.name])
  const tmpl = TEST_TEMPLATES[item.type]
  if (!tmpl) return [['L3', `${item.type} Test`]]
  return tmpl.map(t => [t[0], t[1]])
}

function getEquipName(item) {
  return item.displayName || item.name || DISPLAY_NAMES[item.type] || item.type
}

function getDuration(testCount) {
  if (testCount <= 3) return 1
  if (testCount <= 8) return 2
  if (testCount <= 15) return 3
  if (testCount <= 25) return 4
  return 5
}

function formatDate(date) {
  return date.toISOString().split('T')[0]  // YYYY-MM-DD for API
}

function addDays(date, days) {
  const d = new Date(date)
  d.setDate(d.getDate() + days)
  return d
}

function buildTestChecklist(tests, item) {
  const lines = []
  lines.push(`━━━ TESTS (${tests.length}) ━━━\n`)

  const byLevel = {}
  for (const [level, name] of tests) {
    if (!byLevel[level]) byLevel[level] = []
    byLevel[level].push(name)
  }

  for (const level of ['L1', 'L2', 'L3', 'L4', 'L5']) {
    if (!byLevel[level]) continue
    lines.push(`${LEVEL_LABELS[level] || level}:`)
    for (const name of byLevel[level]) {
      lines.push(`☐ ${name}`)
    }
    lines.push('')
  }

  lines.push(`━━━ INFO ━━━`)
  lines.push(`Equipment: ${DISPLAY_NAMES[item.type] || item.type}`)
  lines.push(`Total tests: ${tests.length}`)
  return lines.join('\n')
}

// ─── MAIN BUILDER ────────────────────────────────────────────────────────────
export async function buildAsanaProject(equipmentData, projectName, onProgress) {
  const progress = (step, total, msg) => {
    if (onProgress) onProgress({ step, total, message: msg })
  }

  // 1. Get workspace
  progress(1, 8, 'Finding workspace...')
  const workspaces = await getWorkspaces()
  if (!workspaces || workspaces.length === 0) throw new Error('No Asana workspaces found')
  const workspace = workspaces[0]  // Use first workspace

  // 2. Create project
  progress(2, 8, 'Creating project...')
  const project = await createProject(
    workspace.gid,
    projectName,
    `HV/MV Substation Commissioning Project\nGenerated by Cx-Dashboard on ${new Date().toLocaleDateString()}\nEquipment items: ${equipmentData.length}`,
    'light-orange'
  )

  // 3. Group equipment by section
  const feederGroups = {}
  for (const item of equipmentData) {
    const ref = item.feeder_ref || 'Unassigned'
    const dashIdx = ref.indexOf(' — ')
    const sectionName = dashIdx >= 0 ? ref.slice(dashIdx + 3) : ref
    if (sectionName === 'Overall') {
      const prefix = dashIdx >= 0 ? ref.slice(0, dashIdx) : ref
      const key = `${prefix} — Overall`
      if (!feederGroups[key]) feederGroups[key] = []
      feederGroups[key].push(item)
    } else {
      if (!feederGroups[sectionName]) feederGroups[sectionName] = []
      feederGroups[sectionName].push(item)
    }
  }

  // 4. Create Milestones section
  progress(3, 8, 'Creating milestones...')
  const msSection = await createSection(project.gid, '🏁 Milestones')
  const baseDate = new Date()
  baseDate.setDate(baseDate.getDate() + 1)

  const milestones = [
    { name: '🏁 Commissioning Kickoff', offset: 0 },
    { name: '📋 L2 Documentation Complete', offset: 14 },
    { name: '⚡ L3 SAT Complete', offset: 49 },
    { name: '🔗 L4 FPT Complete', offset: 63 },
    { name: '🟢 C2E — Ready for Energization', offset: 70 },
    { name: '⚡ ENERGIZATION', offset: 77 },
    { name: '✅ Declaration of Fitness', offset: 84 },
  ]

  const milestoneGids = []
  for (const ms of milestones) {
    const msDate = formatDate(addDays(baseDate, ms.offset))
    const task = await createTask(project.gid, msSection.gid, {
      name: ms.name,
      due_on: msDate,
      resource_subtype: 'milestone',
    })
    milestoneGids.push(task.gid)
    // Small delay to avoid rate limiting
    await new Promise(r => setTimeout(r, 200))
  }

  // 5. Set milestone dependencies (chain them)
  progress(4, 8, 'Setting dependencies...')
  for (let i = 1; i < milestoneGids.length; i++) {
    try {
      await setDependency(milestoneGids[i], milestoneGids[i - 1])
      await new Promise(r => setTimeout(r, 200))
    } catch (e) {
      console.warn('Dependency error (non-critical):', e.message)
    }
  }

  // 6. Create equipment sections + tasks
  progress(5, 8, `Creating ${Object.keys(feederGroups).length} sections...`)
  const sectionNames = Object.keys(feederGroups)
  let taskDayOffset = 0
  let totalTasksCreated = 0

  for (let sIdx = 0; sIdx < sectionNames.length; sIdx++) {
    const sName = sectionNames[sIdx]
    const items = feederGroups[sName]
    progress(6, 8, `Section ${sIdx + 1}/${sectionNames.length}: ${sName}`)

    const section = await createSection(project.gid, sName)
    await new Promise(r => setTimeout(r, 200))

    for (const item of items) {
      const equipName = getEquipName(item)
      const tests = getTests(item)
      const duration = getDuration(tests.length)
      const startDate = formatDate(addDays(baseDate, taskDayOffset))
      const dueDate = formatDate(addDays(baseDate, taskDayOffset + duration))

      const checklist = buildTestChecklist(tests, item)

      await createTask(project.gid, section.gid, {
        name: equipName,
        notes: checklist,
        start_on: startDate,
        due_on: dueDate,
      })

      totalTasksCreated++
      taskDayOffset += Math.max(1, duration - 1)
      await new Promise(r => setTimeout(r, 150))  // Rate limit protection
    }

    taskDayOffset += 1  // Gap between sections
  }

  progress(7, 8, 'Finalising...')

  // 7. Return summary
  progress(8, 8, 'Done!')
  return {
    projectGid: project.gid,
    projectUrl: `https://app.asana.com/0/${project.gid}`,
    totalTasks: totalTasksCreated,
    sections: sectionNames.length,
    milestones: milestones.length,
  }
}
